title: "UTZ Security"
description: "Blog personal de Ciberseguridad — Cristian Huscht"
author: "Cristian Huscht"
theme: minima

# Configuración del blog
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - blog.md
  - about.md
  - contact.md
