title: "UTZ Security"
description: "Blog personal de Ciberseguridad — Cristian Huscht"
author: "Cristian Huscht"
theme: jekyll-theme-cayman
# Configuración del blog
plugins:
  - jekyll-feed
  - jekyll-seo-tag
